# -*- coding: utf-8 -*-
# Twenty more captionsgen.com guides. Imported by genblog.py. Each entry: title, desc, h1, body, rel (3 related slugs).
P = {}

P["subtitles-vs-captions-premiere-pro"] = dict(
title="Subtitles vs Captions in Premiere Pro: What's the Difference?",
desc="Premiere Pro treats subtitles and closed captions differently. Which format to pick, what each one can do, and how to switch between them.",
h1="Subtitles vs captions in Premiere Pro",
rel=["how-to-add-captions-in-premiere-pro","closed-captions-premiere-pro","how-to-add-subtitles-in-premiere-pro"],
body="""
<p>Quick answer: in Premiere Pro, "Subtitle" is the open, styleable text format you burn into the picture, and "closed captions" (CEA-608 and 708) are a data stream the viewer can turn on and off. For social video you want Subtitle. For broadcast delivery you want closed captions.</p>

<h2>What Premiere means by subtitles</h2>
<p>When you click Create captions and pick Subtitle as the format, you get a caption track that you can style freely: any font, size, color, outline and background box. On export you can burn it into the video or save it as a sidecar .srt. This is the format behind almost every captioned Reel, TikTok and Short.</p>

<h2>What Premiere means by closed captions</h2>
<p>CEA-608 and CEA-708 are broadcast standards. The text is stored as data alongside the video, and the player decides whether to display it. Styling is limited by the standard, which is why your fancy font disappears when you pick this format. Broadcasters, streaming services and some accessibility requirements ask for it by name.</p>

<h2>Which one should you use?</h2>
<p>Ask where the video is going. Instagram, TikTok, YouTube Shorts or a website: Subtitle, burned in. A TV network, a streaming platform with a spec sheet, or a client that says "608" or "708": closed captions. YouTube long-form: either a sidecar .srt uploaded as captions, or burned-in subtitles if you want a specific look.</p>

<h2>Switching formats later</h2>
<p>Right-click the caption track header and change the track format. Premiere converts the existing captions, but styling that the new format doesn't support gets dropped, so convert before you style, not after.</p>

<h2>Neither format animates</h2>
<p>Both formats show one static style per track. Word-by-word highlighting, pop-ins and pill backgrounds need a graphics layer instead of a caption track, either built by hand or generated by a plugin.</p>
""")

P["how-to-add-subtitles-in-premiere-pro"] = dict(
title="How to Add Subtitles in Premiere Pro (Auto or From a File)",
desc="Two ways to add subtitles in Premiere Pro: generate them automatically from the audio, or import an .srt file. Styling and export included.",
h1="How to add subtitles in Premiere Pro",
rel=["how-to-add-captions-in-premiere-pro","import-srt-premiere-pro","change-caption-font-premiere-pro"],
body="""
<p>There are two ways to get subtitles into Premiere Pro: let it generate them from the audio, or import a subtitle file you already have. Both end up on the same caption track, styled and exported the same way.</p>

<h2>Way 1: generate subtitles automatically</h2>
<p>Open <kbd>Window &gt; Text</kbd>, click Transcribe sequence, wait for the transcript, then click Create captions with the format set to Subtitle. Premiere places a caption track above your video with every line timed to the speech. For the short-form look, set max characters per line to 16 to 20 before you create them.</p>

<h2>Way 2: import an .srt file</h2>
<p>Go to <kbd>File &gt; Import</kbd>, pick the .srt (or .vtt, .scc), and drag it from the Project panel onto the timeline. Premiere creates a caption track from it. Check that the file's timecodes start where your sequence does; an offset of a few seconds is the usual reason imported subtitles drift.</p>

<h2>Styling the subtitles</h2>
<p>Select any subtitle and open Essential Graphics. Set font, size, fill, stroke and background, then save it as a Track Style so every subtitle on the track matches. One style per track is the limit.</p>

<h2>Exporting</h2>
<p>In the export dialog, open the Captions tab. Burn captions into video for social platforms, or Create sidecar file to hand over an .srt. Leaving it on None exports no subtitles at all, which catches people constantly.</p>

<h2>If you want the subtitles to move</h2>
<p>Native subtitles stay static. For the highlighted-word style, you need a graphics-based approach: either Upgrade caption to graphic and keyframe by hand, or a plugin that generates animated captions with word timing.</p>
""")

P["change-caption-font-premiere-pro"] = dict(
title="How to Change the Caption Font in Premiere Pro",
desc="Change the font, size, color and background of captions in Premiere Pro, apply it to every caption at once with Track Styles, and fix fonts that won't apply.",
h1="How to change the caption font in Premiere Pro",
rel=["best-fonts-for-captions","premiere-pro-caption-presets","how-to-add-captions-in-premiere-pro"],
body="""
<p>Select a caption on the timeline, open <kbd>Window &gt; Essential Graphics</kbd>, and change the font in the Text section. To apply it to every caption on the track, save it as a Track Style. That's the whole procedure; the details below cover the parts that trip people up.</p>

<h2>Step by step</h2>
<ol>
<li>Click one caption on the caption track.</li>
<li>In Essential Graphics, pick the font family and style, set the size, and adjust fill, stroke and background box.</li>
<li>At the top of the panel, open the Track Style dropdown and choose Create Style. Name it. Every caption on the track now uses it.</li>
</ol>

<h2>Why the font only changed on one caption</h2>
<p>Because you edited a single caption instead of the Track Style. Captions on the track follow the Track Style unless you override them individually. Set the style once at track level and the override problem goes away.</p>

<h2>Why the font isn't in the list</h2>
<p>Premiere reads fonts installed in the operating system. Install the font, restart Premiere, and it appears. Adobe Fonts activated through Creative Cloud also show up after a restart.</p>

<h2>Size that reads on a phone</h2>
<p>For vertical video, captions between 5 and 7 percent of the frame height read well on a phone. On a 1080 x 1920 sequence that is roughly 55 to 75 px. Smaller than that and viewers squint; larger and two lines eat the frame.</p>

<h2>What you can't change</h2>
<p>You can't give the spoken word a different color or size from the rest of the line, and you can't animate the font in. Those need a graphic layer rather than a caption track.</p>
""")

P["premiere-pro-caption-presets"] = dict(
title="Premiere Pro Caption Presets: Save and Reuse Caption Styles",
desc="How caption presets and Track Styles work in Premiere Pro, how to save your own, and where ready-made animated caption presets come from.",
h1="Premiere Pro caption presets",
rel=["change-caption-font-premiere-pro","animated-captions-premiere-pro","best-fonts-for-captions"],
body="""
<p>Premiere Pro has two things people mean by "caption preset": the creation preset in the Create captions dialog (line length, lines, format) and the Track Style that controls how captions look. Save both once and captioning a new video takes two clicks.</p>

<h2>Creation presets</h2>
<p>In the Create captions dialog, set your format, max characters per line and number of lines, then use the preset menu at the top to save them. Next time, pick the preset and the settings load. A short-form preset with Subtitle, 18 characters and a single line is the one most people want.</p>

<h2>Track Styles</h2>
<p>Style one caption in Essential Graphics (font, size, color, stroke, background), then choose Create Style from the Track Style dropdown. Track Styles are saved with your project and sync through Creative Cloud libraries if you put them there, so the same look works across projects.</p>

<h2>Sharing presets between machines</h2>
<p>Track Styles live inside the project. To carry them to another computer, put the styled caption into a Library, or keep a template project that you duplicate for every new edit. There is no separate preset file to copy.</p>

<h2>Animated caption presets</h2>
<p>Native presets are static styles. The animated looks you see on social (highlighted word, bounce, pill background) aren't something Premiere's caption track can store. Those presets come from plugins that generate caption graphics, where a preset includes the animation as well as the font and colors.</p>
""")

P["premiere-pro-captions-to-graphics"] = dict(
title="Premiere Pro: Convert Captions to Graphics (and Why)",
desc="How to upgrade captions to graphics in Premiere Pro so you can animate and style them freely, what you lose, and when a plugin is faster.",
h1="Converting captions to graphics in Premiere Pro",
rel=["animated-captions-premiere-pro","word-by-word-captions-premiere-pro","how-to-add-captions-in-premiere-pro"],
body="""
<p>Right-click a caption and choose Upgrade Caption to Graphic. Premiere turns it into a Motion Graphics clip with the same text and timing, sitting on a video track. From there you can animate it like any title.</p>

<h2>Why you'd convert</h2>
<p>The caption track is limited to one static style. A graphic can have keyframes, per-word styling, effects, and any position you like. If you want a caption to pop in, bounce, or highlight one word, it has to be a graphic.</p>

<h2>How to convert all captions at once</h2>
<p>Select every caption on the track (click the first, shift-click the last), then right-click and Upgrade Caption to Graphic. Premiere creates one graphic per caption on a new video track, timed to match.</p>

<h2>What you lose</h2>
<p>Graphics are not captions any more. They won't export as a sidecar .srt, they don't use the Captions tab on export, and the CC toggle in the Program Monitor doesn't affect them. They are simply part of the picture. That is fine for social and wrong for broadcast delivery.</p>

<h2>The time cost</h2>
<p>Converting is instant. Animating is not. Each graphic needs its own keyframes, and a 60-second clip can have 30 to 40 captions. Do it for one hero clip if you like the control; for regular output, a plugin that generates animated caption graphics directly saves the afternoon.</p>
""")

P["premiere-pro-captions-not-exporting"] = dict(
title="Premiere Pro Captions Not Exporting? Here's the Setting",
desc="Captions show in Premiere Pro but not in the exported video? It's almost always the Captions tab in the export dialog. Fix it in 30 seconds.",
h1="Premiere Pro captions not exporting",
rel=["premiere-pro-captions-not-showing","burn-in-captions-premiere-pro","closed-captions-premiere-pro"],
body="""
<p>Open the export dialog, click the Captions tab, and change Export Options from None to Burn Captions Into Video. That fixes it nine times out of ten. The rest of this page covers the tenth.</p>

<h2>The Captions tab</h2>
<p>Premiere does not export captions unless you tell it to, and the setting is on its own tab that many people never open. The choices are None (nothing exported), Create Sidecar File (a separate .srt or similar), and Burn Captions Into Video (text rendered into the picture). For social platforms, burn in.</p>

<h2>Sidecar exported, but the platform shows nothing</h2>
<p>A sidecar file is a separate upload. Instagram and TikTok don't accept it, so burn in for those. YouTube accepts it under Subtitles in the upload flow.</p>

<h2>Closed captions and burn-in</h2>
<p>If your track format is CEA-608 or 708, some export formats only embed the caption data instead of burning it. Convert the track to Subtitle first if you need the text visible in the picture.</p>

<h2>Caption track disabled</h2>
<p>Check the output toggle on the caption track header. A disabled track exports nothing even with burn-in selected.</p>

<h2>Media Encoder queue</h2>
<p>If you send the export to Media Encoder, the caption setting travels with it, but check it there too: reopening the preset in Media Encoder occasionally resets the Captions tab to None.</p>
""")

P["premiere-pro-captions-language"] = dict(
title="Premiere Pro Captions Language: Set, Change and Auto-Detect",
desc="How to set the transcription language in Premiere Pro, what to do when captions come out in the wrong language, and which languages work.",
h1="Setting the caption language in Premiere Pro",
rel=["auto-captions-premiere-pro","premiere-pro-speech-to-text-not-working","how-to-add-captions-in-premiere-pro"],
body="""
<p>The language is set in the Transcribe sequence dialog, not in the caption track. Pick it there before transcribing. If the transcript came out wrong, transcribe again with the right language; there is no way to fix the language on existing captions.</p>

<h2>Where the setting is</h2>
<p>Open <kbd>Window &gt; Text</kbd>, click Transcribe sequence, and use the Language dropdown. Auto detect works for clear single-language speech. For accents, mixed languages, or short clips, choosing the language yourself gives a better transcript.</p>

<h2>Language packs</h2>
<p>Premiere transcribes locally and downloads a language pack the first time you use each language. If the transcribe button seems stuck, check Preferences under Transcription; the pack may still be downloading or may need a manual download.</p>

<h2>Captions came out in the wrong language</h2>
<p>Delete the caption track, open the Transcript tab, click Transcribe sequence again with the correct language, then create captions again. It takes a minute and is the only clean fix.</p>

<h2>Which languages are supported</h2>
<p>Premiere's own transcription covers a fixed set of common languages, and Adobe expands it over time. If yours isn't in the dropdown, a plugin built on Whisper handles a much wider range, close to a hundred languages, with the same auto-detect behavior.</p>

<h2>Two languages in one video</h2>
<p>Premiere transcribes in one language per pass. For bilingual clips, transcribe twice with different languages and keep the correct sections from each, or use a Whisper-based tool that detects language per segment.</p>
""")

P["highlight-words-in-captions-premiere-pro"] = dict(
title="How to Highlight Words in Captions in Premiere Pro",
desc="Premiere Pro's caption track can't highlight the spoken word. Here's the manual way to do it with graphics, and the one-click way with a plugin.",
h1="How to highlight words in captions in Premiere Pro",
rel=["word-by-word-captions-premiere-pro","animated-captions-premiere-pro","premiere-pro-captions-to-graphics"],
body="""
<p>Premiere Pro's caption track applies one style to the whole line, so it cannot highlight the word being spoken. To get that look you need caption graphics: either converted and keyframed by hand, or generated by a plugin that knows when each word starts.</p>

<h2>Why the caption track can't do it</h2>
<p>Captions in Premiere are timed lines of text with a Track Style. There is no word-level timing stored in them and no per-word styling. That is the format's limit, not a missing setting.</p>

<h2>The manual method</h2>
<ol>
<li>Right-click a caption and choose Upgrade Caption to Graphic.</li>
<li>In Essential Graphics, select the word you want highlighted inside the text box and give it a different fill color or size.</li>
<li>Cut the graphic at the point where the next word is spoken, and move the highlight to that word in the new piece.</li>
</ol>
<p>A caption with five words becomes five short graphics. It works and it looks right, but it is slow: expect an hour for a minute of speech.</p>

<h2>The plugin method</h2>
<p>A caption plugin transcribes with word timestamps and builds the highlight for you. You pick the style (color swap, bigger word, pill background), press Generate, and the graphics land on the timeline timed to every word. Changing the highlight color later is a restyle, not a rebuild.</p>

<h2>Which words to highlight</h2>
<p>Highlight the word as it is spoken, not keywords you choose in advance. Viewers read along with the audio, and the moving highlight is what holds attention on muted autoplay.</p>
""")

P["closed-captions-premiere-pro"] = dict(
title="Closed Captions in Premiere Pro: 608, 708 and Broadcast",
desc="How to create CEA-608 and 708 closed captions in Premiere Pro, style within the standard, and export them for broadcast or streaming delivery.",
h1="Closed captions in Premiere Pro",
rel=["subtitles-vs-captions-premiere-pro","premiere-pro-captions-not-exporting","how-to-add-captions-in-premiere-pro"],
body="""
<p>Closed captions in Premiere Pro are created the same way as subtitles, with the format set to CEA-608 or CEA-708 in the Create captions dialog. The difference is what happens after: styling is limited to what the standard allows, and export embeds the captions as data or writes a sidecar file.</p>

<h2>608 or 708?</h2>
<p>CEA-608 is the older standard with basic styling and channel limits. CEA-708 is the modern digital standard with more styling options and multiple services. If your delivery spec doesn't say, 708 is the safer default; many deliverables ask for both.</p>

<h2>Creating them</h2>
<p>Transcribe the sequence, click Create captions, choose the closed caption format, and set the line length the spec requires (32 characters is the common 608 limit). Premiere enforces the standard's rules as you edit, so a line that is too long gets flagged.</p>

<h2>Styling limits</h2>
<p>You can set position, a small set of colors, and background boxes. You cannot use custom fonts. That's by design; the viewer's device renders the captions with its own font.</p>

<h2>Exporting</h2>
<p>In the export dialog's Captions tab, choose Create Sidecar File (.scc for 608, .mcc or .xml for 708 depending on the spec) or embed the captions in the video stream where the format allows it. Burn-in is available too, but it defeats the point of closed captions.</p>

<h2>Checking your output</h2>
<p>Import the exported file back into a new Premiere project and enable CC in the Program Monitor. If captions show, the file is valid.</p>
""")

P["how-to-add-text-in-premiere-pro"] = dict(
title="How to Add Text in Premiere Pro (Titles and Lower Thirds)",
desc="Add text to a video in Premiere Pro with the Type tool, style it in Essential Graphics, and know when to use captions instead of titles.",
h1="How to add text in Premiere Pro",
rel=["how-to-add-captions-in-premiere-pro","best-fonts-for-captions","premiere-pro-captions-to-graphics"],
body="""
<p>Press T for the Type tool, click in the Program Monitor, and type. Premiere creates a graphic clip on the track above your video. Style it in <kbd>Window &gt; Essential Graphics</kbd>. That covers titles and lower thirds; for spoken dialogue, use captions instead.</p>

<h2>Adding a title</h2>
<ol>
<li>Park the playhead where the text should start.</li>
<li>Select the Type tool (T) and click in the Program Monitor.</li>
<li>Type, then press Escape. Drag the clip's edges on the timeline to set how long it stays.</li>
</ol>

<h2>Styling</h2>
<p>With the graphic selected, Essential Graphics shows font, size, fill, stroke, shadow and background options. Align to the frame with the alignment buttons at the top so text sits centered or on the safe margins.</p>

<h2>Animating</h2>
<p>Open the Effect Controls panel, toggle the stopwatch on Position, Scale or Opacity, and set keyframes. For a quick fade, right-click the clip and Apply Default Transitions.</p>

<h2>When to use captions instead</h2>
<p>If the text is what someone is saying, don't type it as titles. Transcribe the sequence and create captions; it's automatic and stays in sync with the audio. Titles are for names, headings and words that aren't spoken.</p>

<h2>Text that follows the speech word by word</h2>
<p>That's animated captions territory. Premiere's caption track can't do it and typing titles by hand is impractical. A caption plugin generates those graphics from the audio.</p>
""")

P["free-caption-plugin-premiere-pro"] = dict(
title="Free Caption Plugins for Premiere Pro: What Actually Works",
desc="Free ways to get auto captions in Premiere Pro: the built-in tool, free trials of caption plugins, and what each one gives you for nothing.",
h1="Free caption plugins for Premiere Pro",
rel=["best-caption-plugin-premiere-pro","auto-captions-premiere-pro","animated-captions-premiere-pro"],
body="""
<p>The most complete free option is already inside Premiere: its own speech-to-text makes static captions at no cost. For animated captions, most plugins are paid, and the free route is a trial or a free tier with a limit. Here is what you get for free from each approach.</p>

<h2>Premiere's built-in captions (free, unlimited)</h2>
<p>Transcribe sequence, Create captions, done. Unlimited minutes, runs offline, decent accuracy. Its limit is the look: one static style per track, no word highlighting, no animation.</p>

<h2>Free tiers of caption plugins</h2>
<p>Plugins that animate captions usually charge, because word-level transcription and the caption templates are the product. Some offer a trial with a minute cap or a watermark. Read the limit before you build a workflow around it; a watermark on client work is a bad surprise.</p>

<h2>Captions Gen's free version</h2>
<p><a href="https://captionsgen.com/">Captions Gen</a> has a free version with 15 minutes of transcription and no watermark. Everything else is the full plugin: karaoke highlighting, presets, live preview, restyle. Fifteen minutes is enough for ten to fifteen short clips, so you can decide with real projects. The paid version is a one-time $14.99.</p>

<h2>The CapCut route</h2>
<p>CapCut's auto captions are free, but you leave Premiere, round-trip the video, and bring back burned-in text you can't edit. Free in money, expensive in time on every revision.</p>

<h2>Pick by what you're making</h2>
<p>Documentary-style subtitles: Premiere's own tool. Short-form with animated captions: a plugin, tested through its free tier first.</p>
""")

P["best-caption-plugin-premiere-pro"] = dict(
title="Best Caption Plugin for Premiere Pro in 2026: How to Choose",
desc="What separates caption plugins for Premiere Pro: transcription quality, native graphics, animation styles, pricing. A checklist, and where Captions Gen fits.",
h1="Choosing the best caption plugin for Premiere Pro",
rel=["free-caption-plugin-premiere-pro","animated-captions-premiere-pro","capcut-vs-premiere-pro-captions"],
body="""
<p>Several plugins now add animated captions to Premiere Pro, and they differ on five things: where transcription runs, whether captions land as native graphics, what animations exist, how fast you can restyle, and what you pay. Check those five and the choice makes itself.</p>

<h2>1. Local or cloud transcription</h2>
<p>Cloud transcription means uploading your client's footage to someone's server and often paying per minute. Local transcription (Whisper on your machine) is private and has no meter. Ask which one a plugin uses before anything else.</p>

<h2>2. Native graphics or rendered files</h2>
<p>The good plugins place Motion Graphics clips you can open in Essential Graphics to fix a word or nudge timing. Some produce rendered video overlays instead, which are dead the moment the edit changes.</p>

<h2>3. Animation styles</h2>
<p>At minimum: highlighted spoken word (color swap and pill), pop or bounce on the word, in and out animations for the caption. Presets that bundle font, color and animation save the most time.</p>

<h2>4. Restyle speed</h2>
<p>You will change your mind about the look. A plugin that restyles the whole sequence without transcribing again turns that into seconds instead of a rebuild.</p>

<h2>5. Pricing</h2>
<p>Subscriptions add up for a tool you use a few times a week. One-time purchases are rarer and worth preferring at this price range.</p>

<h2>Where Captions Gen lands</h2>
<p><a href="https://captionsgen.com/">Captions Gen</a> transcribes locally, places native editable graphics, ships karaoke highlighting with pill and color-swap styles plus bounce and in/out animations, restyles a sequence in seconds, and costs $14.99 once. It is Windows-only for now. Test it with the free version before deciding.</p>
""")

P["word-by-word-captions-premiere-pro"] = dict(
title="Word by Word Captions in Premiere Pro (One Word at a Time)",
desc="How to make captions appear one word at a time in Premiere Pro: the manual way with graphics and cuts, and the automatic way with a plugin.",
h1="Word by word captions in Premiere Pro",
rel=["highlight-words-in-captions-premiere-pro","animated-captions-premiere-pro","captions-for-tiktok-reels-shorts-premiere-pro"],
body="""
<p>Two looks go by this name: one word on screen at a time, or a full line where the spoken word lights up. Premiere's caption track can do a rough version of the first and none of the second. Both are quick with a plugin.</p>

<h2>One word at a time, natively</h2>
<p>In the Create captions dialog, set max characters per line to something tiny, like 8. Premiere splits the transcript into very short captions, often single words. Timing follows the transcript, so it roughly matches speech. Styling is still one Track Style, and long words wrap awkwardly.</p>

<h2>Spoken word highlighted in a full line</h2>
<p>This is the karaoke look and the caption track can't do it. The manual route is Upgrade Caption to Graphic, then cut the graphic at each word and change that word's color in each piece. Accurate, and about an hour per minute of speech.</p>

<h2>The automatic route</h2>
<p>A caption plugin transcribes with word timestamps and generates caption graphics where each word activates on time. You choose whether the word changes color, grows, or gets a pill behind it, and whether it bounces. The captions stay editable graphics on the timeline.</p>

<h2>How many words per caption</h2>
<p>For vertical video, three to five words per caption reads best. One word at a time is punchy but tiring over a minute; a full line with a moving highlight keeps the rhythm without the strain.</p>
""")

P["captions-for-tiktok-reels-shorts-premiere-pro"] = dict(
title="Captions for TikTok, Reels and Shorts in Premiere Pro",
desc="Set up captions for vertical video in Premiere Pro: sequence settings, safe zones, size, line length, and the animated style that holds attention.",
h1="Captions for TikTok, Reels and Shorts in Premiere Pro",
rel=["word-by-word-captions-premiere-pro","best-fonts-for-captions","burn-in-captions-premiere-pro"],
body="""
<p>Vertical captions need four things: a 1080 x 1920 sequence, text kept out of the platform's UI zones, a size that reads on a phone, and short lines. Premiere handles the first three natively. The animated style that most viral clips use needs a plugin.</p>

<h2>Sequence settings</h2>
<p>Make the sequence 1080 x 1920 (9:16) at your footage's frame rate. Captioning a horizontal sequence and cropping later leaves the text in the wrong place.</p>

<h2>Safe zones</h2>
<p>TikTok, Reels and Shorts overlay buttons on the right edge and text at the bottom. Keep captions in the center band, roughly the middle 60 percent of the height, and away from the right third. Slightly above center works on all three platforms.</p>

<h2>Size and line length</h2>
<p>Font size between 55 and 75 px on a 1920-tall frame. Max 16 to 20 characters per line, single line. Bold sans fonts with a stroke or background box survive busy footage.</p>

<h2>Timing</h2>
<p>Short-form viewers read fast but not instantly. Keep each caption on screen for at least 0.8 seconds, and split long sentences at the natural pause rather than at a character count. If Premiere's auto split lands mid-phrase, merge or razor the captions by hand; it takes a minute per clip and reads much better.</p>

<h2>Export</h2>
<p>Burn the captions in from the export dialog's Captions tab. These platforms don't accept sidecar files.</p>

<h2>The animated look</h2>
<p>Most high-performing clips highlight the spoken word or show words one by one. Premiere's caption track can't do that, so editors either keyframe graphics by hand or use a caption plugin that generates the animation from the audio.</p>
""")

P["import-srt-premiere-pro"] = dict(
title="Import and Export SRT Subtitle Files in Premiere Pro",
desc="How to import an .srt into Premiere Pro as a caption track, fix timing offsets, style it, and export an .srt sidecar from your captions.",
h1="Import and export SRT files in Premiere Pro",
rel=["how-to-add-subtitles-in-premiere-pro","fix-caption-timing-premiere-pro","premiere-pro-captions-not-exporting"],
body="""
<p>Import: <kbd>File &gt; Import</kbd> the .srt, then drag it from the Project panel onto the timeline; Premiere builds a caption track from it. Export: in the export dialog's Captions tab, choose Create Sidecar File and pick SRT.</p>

<h2>Importing</h2>
<p>Premiere accepts .srt, .vtt, .scc, .mcc and a few others. After import the file sits in the Project panel like a clip. Drop it on the timeline above your video and it becomes a caption track using the Subtitle format.</p>

<h2>Fixing an offset</h2>
<p>If the imported captions are early or late by a constant amount, select all captions on the track and drag them together. If the drift grows over time, the .srt was made for a different frame rate or a trimmed version of the video; re-export it from the source or re-transcribe in Premiere.</p>

<h2>Styling an imported .srt</h2>
<p>Same as any caption track: style one caption in Essential Graphics and save it as a Track Style.</p>

<h2>Exporting an .srt</h2>
<p>Open the export dialog, go to Captions, choose Create Sidecar File, and set the format to SRT. The file lands next to the video. Upload it to YouTube under Subtitles, or hand it to a translator.</p>

<h2>SRT and animated captions</h2>
<p>SRT stores lines and times, not word timing or animation. Caption plugins that animate word by word keep their own word timestamps; the caption graphics they place can't be exported as .srt, so keep the native caption track too if you need both.</p>
""")

P["premiere-pro-speech-to-text-not-working"] = dict(
title="Premiere Pro Speech to Text Not Working? 7 Things to Check",
desc="Transcribe sequence greyed out, stuck, or producing garbage? Seven causes of Premiere Pro speech to text problems and the fix for each.",
h1="Premiere Pro speech to text not working",
rel=["auto-captions-premiere-pro","premiere-pro-captions-language","premiere-pro-captions-not-showing"],
body="""
<p>Most speech-to-text failures in Premiere Pro come down to a missing language pack, the wrong audio track, or an audio clip Premiere can't read. Check these seven in order.</p>

<h2>1. The language pack isn't installed</h2>
<p>Premiere downloads a pack per language the first time. Open Preferences, find Transcription, and check the language's status. A stalled download looks like a transcribe button that does nothing.</p>

<h2>2. Wrong audio track selected</h2>
<p>In the Transcribe dialog, choose the track that holds the dialogue. Transcribing a music track returns nonsense or nothing.</p>

<h2>3. The audio is muted or disabled</h2>
<p>A muted track or a clip with audio disabled transcribes as silence. Unmute and try again.</p>

<h2>4. Auto detect picked the wrong language</h2>
<p>Set the language manually in the dialog. Accents and short clips confuse auto detect.</p>

<h2>5. Very long sequence</h2>
<p>Transcribing an hour of audio takes a while and looks frozen. Transcribe in and out points instead of the whole sequence, or wait it out.</p>

<h2>6. Outdated Premiere</h2>
<p>Speech to text moved from cloud to local in 2022 and has changed since. Update through Creative Cloud; old versions have known transcription bugs.</p>

<h2>7. Corrupt cache</h2>
<p>Clear the media cache in Preferences and restart. It resolves a surprising number of "stuck at 0 percent" cases.</p>

<h2>Still nothing</h2>
<p>Export the audio as a WAV, import it fresh, and transcribe that. If it works, the original clip's audio encoding was the problem. Whisper-based plugins read almost anything, which is another way around a stubborn file.</p>
""")

P["fix-caption-timing-premiere-pro"] = dict(
title="Fix Caption Timing in Premiere Pro: Early, Late, Overlapping",
desc="Captions out of sync in Premiere Pro? How to shift, retime, split and merge captions, and why auto captions drift after an edit.",
h1="Fix caption timing in Premiere Pro",
rel=["premiere-pro-captions-not-showing","import-srt-premiere-pro","how-to-add-captions-in-premiere-pro"],
body="""
<p>Captions in Premiere Pro are clips on a caption track, so you fix timing the way you fix any clip: drag edges to retime, drag the whole thing to shift, and use the razor to split. For a constant offset, select all and move them together.</p>

<h2>Everything is off by the same amount</h2>
<p>Click the first caption, shift-click the last, and drag. Hold the playhead on a word you can hear and line the caption up to it. Imported .srt files cause this most often.</p>

<h2>Captions drift over time</h2>
<p>A drift that grows means the captions were made for a different cut. If you trimmed the video after transcribing, the captions after the cut are all late by the length you removed. Re-transcribe after locking the edit, or select everything after the cut and shift it.</p>

<h2>Two captions overlap</h2>
<p>Trim the first caption's out point to the second's in point. Overlapping captions flicker or fail to render in some players.</p>

<h2>A caption is too long or too short</h2>
<p>Split it with the razor at the natural pause, or select two and choose Merge Captions from the right-click menu. Aim for captions of one to three seconds.</p>

<h2>Word-level timing</h2>
<p>Native captions store timing per line only. If you need timing per word, for highlighted captions, that comes from a plugin's transcription rather than the caption track.</p>
""")

P["capcut-vs-premiere-pro-captions"] = dict(
title="CapCut vs Premiere Pro Captions: Which Should You Use?",
desc="CapCut's auto captions vs Premiere Pro's: accuracy, styling, animation, editing, and how to get CapCut-style captions without leaving Premiere.",
h1="CapCut vs Premiere Pro captions",
rel=["animated-captions-premiere-pro","best-caption-plugin-premiere-pro","captions-for-tiktok-reels-shorts-premiere-pro"],
body="""
<p>CapCut wins on caption style, Premiere wins on everything else about editing. That's why so many editors round-trip: edit in Premiere, caption in CapCut, bring it back. A caption plugin removes the reason for the trip.</p>

<h2>Styling and animation</h2>
<p>CapCut has dozens of animated caption templates with word highlighting, built for TikTok. Premiere's caption track has one static style per track and no animation. On looks alone, CapCut is ahead.</p>

<h2>Accuracy</h2>
<p>Both are reasonable on clean speech. Premiere transcribes locally, CapCut in the cloud. Names and technical words need fixing in either.</p>

<h2>Editing after captioning</h2>
<p>In Premiere, captions are clips you can retime, restyle and correct at any point. CapCut's captions come back as burned-in pixels, so a typo means redoing the trip.</p>

<h2>Privacy</h2>
<p>CapCut uploads your footage. Premiere doesn't. For client work under NDA, that decides it.</p>

<h2>Time per revision</h2>
<p>The round trip costs an export, a caption pass, another export and an import, every time the edit changes. Plugins that generate animated captions inside Premiere cost none of that.</p>

<h2>Cost</h2>
<p>CapCut's auto captions are free on the app's basic tier, with some templates behind CapCut Pro. Premiere's captions are included in the subscription you already pay. A caption plugin is a one-time purchase on top; whether it pays off depends on how many round trips it saves you per month.</p>

<h2>Getting the CapCut look in Premiere</h2>
<p>A plugin like <a href="https://captionsgen.com/">Captions Gen</a> generates the highlighted-word style as native graphics on your timeline. Same look, no export loop, and captions you can still edit.</p>
""")

P["best-fonts-for-captions"] = dict(
title="Best Fonts for Captions and Subtitles (With Sizes)",
desc="Fonts that read on a phone at speed: bold sans faces that work for short-form captions, plus sizes, stroke and background settings that keep them legible.",
h1="Best fonts for captions and subtitles",
rel=["change-caption-font-premiere-pro","captions-for-tiktok-reels-shorts-premiere-pro","premiere-pro-caption-presets"],
body="""
<p>Caption fonts have one job: be readable in under a second on a phone over moving footage. That rules out thin weights, scripts and anything condensed to the point of blurring. Bold, wide sans faces win, and a stroke or background box does more for legibility than any font choice.</p>

<h2>Fonts that work</h2>
<ul>
<li>Montserrat ExtraBold or Black. The default look of a lot of short-form video.</li>
<li>Poppins Bold. Rounder, friendlier, same readability.</li>
<li>Anton and Bebas Neue. Tall, loud, good for a single word on screen; less good for full lines.</li>
<li>Impact. Old, but on a phone at 60 px it still reads.</li>
<li>Inter Bold or Arial Black. Neutral when the brand has its own personality elsewhere.</li>
</ul>

<h2>Fonts that fail</h2>
<p>Anything below semibold weight, italic-only faces, script fonts, and typewriter fonts. They read fine on a monitor and vanish on a phone in daylight.</p>

<h2>Size</h2>
<p>On a 1080 x 1920 frame, 55 to 75 px. Go bigger for single-word captions, smaller for two-line captions.</p>

<h2>Stroke and background</h2>
<p>A dark stroke of 4 to 8 px, or a semi-transparent black box behind the text, keeps captions readable over bright footage. Pick one; both together look heavy.</p>

<h2>Case</h2>
<p>All caps reads faster at small sizes and matches the short-form style. Sentence case feels calmer for interviews and documentary edits.</p>

<h2>Applying it in Premiere</h2>
<p>Set the font once in Essential Graphics and save it as a Track Style. If you use a caption plugin, save the combination as a preset and the animation comes along.</p>
""")

P["burn-in-captions-premiere-pro"] = dict(
title="How to Burn In Captions in Premiere Pro (Export Settings)",
desc="Burn captions into the video in Premiere Pro so they show on every platform: the exact export setting, quality tips, and when a sidecar is better.",
h1="How to burn in captions in Premiere Pro",
rel=["premiere-pro-captions-not-exporting","captions-for-tiktok-reels-shorts-premiere-pro","closed-captions-premiere-pro"],
body="""
<p>Open the export dialog, click the Captions tab, set Export Options to Burn Captions Into Video, and export. The text becomes part of the picture and shows everywhere, on every player, with no CC button involved.</p>

<h2>When to burn in</h2>
<p>Instagram, TikTok, YouTube Shorts, LinkedIn, and any platform that doesn't accept caption files. Also whenever you styled the captions and want that exact look preserved.</p>

<h2>When not to</h2>
<p>Broadcast delivery, or YouTube long-form where viewers may want captions off or translated. Use a sidecar file or closed captions there.</p>

<h2>Quality</h2>
<p>Burned-in text is compressed with the video. Small text with thin strokes turns muddy at low bitrates. Use bold fonts, sizes above 55 px on vertical video, and a bitrate of at least 10 Mbps for 1080p vertical exports.</p>

<h2>Export format</h2>
<p>H.264 in an MP4 container is what every social platform expects, and burn-in works with it. If you export ProRes or another mezzanine format for a colorist, burn-in still works, but consider leaving captions off that master and burning them into the delivery file instead, so the master stays clean.</p>

<h2>Checking before you post</h2>
<p>Scrub the exported file at a few points. If captions are missing entirely, the Captions tab was on None; re-export.</p>

<h2>Animated captions and burn-in</h2>
<p>Caption graphics made by a plugin are video layers, not captions, so they are always in the picture regardless of the Captions tab. No setting to remember.</p>
""")
